name: Main

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 15 with NPM 7
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run publish
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "moodle-buddy.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
